services:
  nestjs-microservice:
    build:
      context: .
      dockerfile: apps/nestjs-microservice/Dockerfile
      target: development
    command: npm run start:dev
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
  auth:
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    ports:
      - '3001:3001'
  mongo:
    image: mongo